# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

# Change the default prompt format
format = """\
[╭╴](238)$env_var\
$all[╰─](238)$character"""
#

# ~/.config/starship.toml

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "🅰 "
[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"
[aws.profile_aliases]
CompanyGroupFrobozzOnCallAccess = 'Frobozz'

[azure]
disabled = false
format = "on [$symbol($subscription)]($style) "
symbol = "ﴃ "
style = "blue bold"

#battery

[battery]
charging_symbol = "⚡️ "
discharging_symbol = "💦 "
full_symbol = "🔋 "

[[battery.display]] # "bold red" style and discharging_symbol when capacity is between 0% and 20%
threshold = 20
style = "bold red"

[[battery.display]] # "bold purple" style and 💦 symbol when capacity is between 20% and 45%
threshold = 45
style = "bold purple"

[[battery.display]] # "bold yellow" style and 💦 symbol when capacity is between 45% and 75%
threshold = 75
style = "bold yellow"

[[battery.display]] # "bold yellow" style and 💦 symbol when capacity is between 75% and 99%
threshold = 99
style = "bold green"

[[battery.display]]
threshold = 101
style = "bold green"

# C file

[c]
style = "bold 149 blue"
symbol = " "

# Change the default prompt characters

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[crystal]
format = "via [✨ $version](bold blue) "

[dart]
format = "via [🔰 $version](bold red) "

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

[docker_context]
format = "via [ $context](bold blue) "

[dotnet]
symbol = "🥅 "
heuristic = false


# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](white)'
variable = "STARSHIP_DISTRO"
disabled = false

[git_branch]
symbol = " "
format = "via [$symbol$branch]($style) "
truncation_length = 10
truncation_symbol = "…/"

[git_commit]
commit_hash_length = 10
tag_symbol = "🔖 "
# only_detached = false
# tag_disabled = false

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳 "
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[helm]
format = "via [ $version](bold purple) "

[hostname]
ssh_only = false
ssh_symbol = "🌏 "
format = "[$ssh_symbol](bold blue) on [$hostname](bold yellow) "
disabled = false

[java]
symbol = " "

[jobs]
symbol = "✦ "
number_threshold = 1
symbol_threshold = 1

[julia]
symbol = "∴ "

[kotlin]
symbol = "🅺  kotlinc"
style = "bold purple"

[kubernetes]
format = 'via [ﴱ $context\($namespace\)](bold purple) '
disabled = false

[kubernetes.context_aliases]
"do-fra1-prod-k8s-clcreative" = " lgcy-1"
"infra-home-kube-prod-1" = " prod-1"
"infra-home-kube-prod-2" = " prod-2"
"infra-cloud-kube-prod-1" = " prod-1"
"infra-cloud-kube-test-1" = " test-1"

[memory_usage]
disabled = false
threshold = 80
symbol = " "
style = "bold dimmed green"

[nodejs]
format = "via [$symbol($version)](bold green) "
disabled = false
symbol = " "

[package]
symbol = "🎁 "

[php]
format = "via [$symbol php($version )]($style)"

[ruby]
format = "via [$symbol ($version)]($style) "
#symbol = " "

# Shows the username
[username]
style_user = "white"
style_root = "white"
format = "[$user]($style) "
disabled = false
show_always = true

[terraform]
format = "via [ terraform $version]($style) 壟 [$workspace]($style) "

[vagrant]
format = "via [ vagrant $version]($style) "






